# main.py
"""
LangGraph Multi-Agent Research & Writing System — CLI Entry Point.

Usage:
    python main.py
    
    Enter a topic when prompted, and watch the 7-agent pipeline:
    Planner → Researcher → Analyst → Writer → Reviewer → [Reviser] → Finalizer
"""

import sys
from pathlib import Path

# Ensure the project root is in the Python path
PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.research_graph import build_research_graph


def print_separator(char: str = "=", length: int = 60) -> None:
    """Print a visual separator for CLI output."""
    print(char * length)


def print_header() -> None:
    """Print the application header."""
    print_separator()
    print("🦁  LangGraph Multi-Agent Research & Writing System")
    print("   Planner → Researcher → Analyst → Writer → Reviewer → Finalizer")
    print_separator()


def get_topic() -> str:
    """Get research topic from user input with a default fallback."""
    print("\n📝  Enter a research topic (or press Enter for default):")
    topic = input("    Topic: ").strip()

    if not topic:
        topic = (
            "The impact of Agentic AI on enterprise software development "
            "and how multi-agent systems are transforming automation"
        )
        print(f"    Using default topic: {topic}")
        print()

    return topic


def display_plan(state: dict) -> None:
    """Display the research plan generated by the Planner agent."""
    plan = state.get("plan", [])
    print(f"\n📋  Research Plan ({len(plan)} questions):")
    for i, question in enumerate(plan, 1):
        print(f"    {i}. {question}")


def display_results_summary(state: dict) -> None:
    """Display a summary of the pipeline results."""
    print(f"\n📊  Pipeline Statistics:")
    print(f"    • Plan questions:   {len(state.get('plan', []))}")
    print(f"    • Search results:   {len(state.get('search_results', []))} batches")
    print(f"    • Revisions:        {state.get('revision_count', 0)}")
    print(f"    • Approved:         {'✅ Yes' if state.get('approved', False) else '❌ No (force-finalized)'}")


def display_final_output(state: dict) -> None:
    """Display the final article output."""
    print_separator()
    print("📰  FINAL ARTICLE")
    print_separator()
    print()
    print(state.get("final_output", "⚠️  No output generated."))
    print()
    print_separator()


def main() -> None:
    """Main entry point for the CLI application."""
    print_header()
    topic = get_topic()

    print("🔄  Running multi-agent pipeline...")
    print("    (This may take 30-60 seconds depending on API latency)\n")

    # Build the compiled graph
    graph = build_research_graph()

    # Prepare initial state
    initial_state = {
        "topic": topic,
        "plan": [],
        "search_results": [],
        "research_summary": "",
        "draft": "",
        "feedback": None,
        "approved": False,
        "final_output": None,
        "revision_count": 0,
        "max_revisions": 2,  # Safety limit: max 2 revision cycles
    }

    # Invoke the graph with a thread_id for checkpointing
    # This enables: session tracking, resume capability, audit trail
    config = {"configurable": {"thread_id": "cli-session-001"}}

    try:
        result = graph.invoke(initial_state, config)
    except Exception as e:
        print(f"\n❌  Pipeline failed: {e}")
        print("    Check your DEEPSEEK_API_KEY in the .env file.")
        sys.exit(1)

    # Display results
    display_plan(result)
    display_results_summary(result)
    display_final_output(result)

    print("✅  Pipeline completed successfully!")
    print("    Thread ID: cli-session-001 (for debugging/audit)")
    print()


if __name__ == "__main__":
    main()