# src/state.py
"""
Shared State definition for the Multi-Agent Research & Writing System.
LangGraph passes this TypedDict between all nodes in the graph.

This is the "envelope" that travels through every agent — each agent
reads from it and writes to it, creating a traceable audit trail.
"""

from typing import TypedDict, List, Optional


class AgentState(TypedDict):
    """
    Shared state flowing through all agents in the pipeline.

    Design Decision: Using TypedDict (not Pydantic) because LangGraph
    natively supports it for checkpoint serialization, and it's lighter
    weight than full Pydantic models for graph state.
    """

    # ── Input ──────────────────────────────────────
    topic: str
    """The research/writing topic provided by the user."""

    # ── Planner Output ─────────────────────────────
    plan: List[str]
    """3-5 focused research questions generated by the Planner agent."""

    # ── Researcher Output ──────────────────────────
    search_results: List[str]
    """Synthesized search results for each plan question."""

    # ── Analyst Output ─────────────────────────────
    research_summary: str
    """Structured research summary with findings and evidence."""

    # ── Writer Output ──────────────────────────────
    draft: str
    """The first draft of the article (500-800 words)."""

    # ── Reviewer Output ────────────────────────────
    feedback: Optional[str]
    """Revision feedback from the Reviewer agent (None if approved)."""

    approved: bool
    """True if the Reviewer approves the draft for finalization."""

    # ── Finalizer Output ───────────────────────────
    final_output: Optional[str]
    """The polished, approved final article."""

    # ── Safety & Control ───────────────────────────
    revision_count: int
    """Number of revision loops executed (safety counter)."""

    max_revisions: int
    """Maximum allowed revisions before force-finalizing (prevents infinite loops)."""